version: '3.8'
services:
  api:
    # image from docker hub repo  
    image: kevinrooso/mybooksapi
    # Node app listens on 4000 port
    ports:
      - '4000:4000'
  bookapp:    
    image: kevinrooso/mybooksapp
    # Running React Vite app on port 80
    ports:
      - '80:80'
    # Stdin open makes the standard user input open which is good for development commands like in
    # React we might want to run npm commands 
    stdin_open: true
    # TTy refers to providing terminal interface for container where we can use the commands mentioned 
    # above    
    tty: true      